# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kai Cheng
title: Incoming Master Student at Columbia University in the City of New York
email: tw841117@gmail.com
website: kaiicheng.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: kaiiicheng
github_username:  kaiicheng
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kaiicheng
linkedin_username: kaiicheng
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Kai and I'm an incoming statistics/data science master student. As well as statistics, I also have experience conducting academic and market researh. I have worked at a number of companies and student associations gaining teamwork and leadership skills.

  I am most skilled in: <mark>Statistics</mark> and <mark>Python</mark>.

# Education.
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Columbia University in the City of New York
        caption: 2020 (deferred)
        sub_title: Master of Quantitative Methods - Data Science track
        quote: >
          New York City, New York
        description: | # this will include new lines to allow paragraphs
          Due to COVID-19 pandemic, I deferred my admission to 2021 and chose to become a visiting student at National Taiwan University.

      - layout: left
        title: National Taiwan University
        caption: 2021 - Present (visiting studnet)
        sub_title: Master of Electrical Engineering - Computer Science Major
        quote: >
          Taipei, Taiwan
        description: | # this will include new lines to allow paragraphs
          Relevant Coursework: Advanced Statistics II, Data Structures & Algorithms, Machine Learning, Operation Systems, Computer Architecture. Computer Programming, Introduction to Computer Science.

      - layout: left
        title: National Taiwan University
        caption: 2020 - 2021 (visiting studnet)
        sub_title: Master of Business Administration - Operations Management & Business Analytics Major
        quote: >
          Taipei, Taiwan
        description: | # this will include new lines to allow paragraphs
          Relevant Coursework: Statistics, Advanced Statistics I, Discrete Mathematics, Linear Algebra, Optimization Methods, Database Management, Programming for Business Computing in Python.

      - layout: left
        title: National Taiwan University
        caption: 2014 - 2018
        sub_title: Bachelor of Sociology
        quote: >
          Taipei, Taiwan
        description: | # this will include new lines to allow paragraphs
          Relevant Coursework: Social Statistics, Social Research Method, Introductory Sociology, Calculus, International Finance, Business Management, Accounting Principles, Economic Sociology, Social Organization, Principles of Economics.

# Research experience.
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Academia Sinica (中央研究院)
        link: sinica.edu.tw/en
        # link_text: boringcompany.com
        sub_title: Statistical Assistant
        caption: March 2019 - February 2020
        quote: >
          Taipei, Taiwan
        description: | # this will include new lines to allow paragraphs
          Assisted in social science, population and healthcare comparative study between European Union members and Asian countries, analyzed combinations between GNI, GDP and other factors to predict health conditions and life expectancy.

      - layout: left
        title: Population Association of Taiwan (臺灣人口學會)
        link: paotw.org
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: March 2019 - July 2019
        quote: >
          Taipei, Taiwan
        description: | # this will include new lines to allow paragraphs
          Collected demographic and population data, analyzed relationships between factors by running the independent t-test, chi-square test, and one-way ANOVA with Stata and SPSS and visualized data with Tableau and Python.

# Work experience.
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
